CREATE TABLE dbname (
    id INT(6) UNSIGNED AUTO_INCREMENT PRIMARY KEY,
    temperature FLOAT(10),
    humidity FLOAT(10),
    reading_time TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
    );